let data = [{ id: 1, name: 'Nevada Discount Nutrition' },
{ id: 2, name: 'Mariana\'s Supermarket' },
{ id: 3, name: 'Las Vegas Orthodontics' },
{ id: 4, name: 'Carolina Community Maternity Center' },
{ id: 5, name: 'Little Shop of Cookies' },
{ id: 6, name: 'Furniture Row' },
{ id: 7, name: 'Sport Clips Haircuts of Mesa' },
{ id: 8, name: 'Adam Pollock, DDS' },
{ id: 9, name: 'Dear-Born baby' },
{ id: 10, name: 'Chenoy\'s Delicatessen' },
{ id: 11, name: 'Heirloom Photo Studio' },
{ id: 12, name: 'Technical Grace' },
{ id: 13, name: 'Embassy Suites by Hilton Montreal' },
{ id: 14, name: 'Transformative Voice with Wendy Vastine' },
{ id: 15, name: 'Norman Felix' },
{ id: 16, name: 'Advance Auto Parts' },
{ id: 17, name: 'Smashburger' },
{ id: 18, name: 'Paramount Fine Foods' },
{ id: 19, name: 'Office Max' },
{ id: 20, name: 'Staybridge Suites Akron-Stow-Cuyahoga Falls' },
{ id: 21, name: 'Kennedy Chiropractic Clinics' },
{ id: 22, name: 'myspa' },
{ id: 23, name: 'Flowers by Renee' },
{ id: 24, name: 'Artistic Design Dentistry' },
{ id: 25, name: 'Potbelly Sandwich Shop' },
{ id: 26, name: 'Salon Tocci' },
{ id: 27, name: 'Max & Erma\'s Restaurants' },
{ id: 28, name: 'Sree\'s Foods' },
{ id: 29, name: 'Integrity Valet' },
{ id: 30, name: 'Hollow Ground Barber Shop' },
{ id: 31, name: 'Chandler Memory Care' },{ id: 32, name: 'Griddlecakes' },
{ id: 33, name: 'Tea Shop 168' },
{ id: 34, name: 'Mixed Pet Veterinary Hospital - Stonecrest' },
{ id: 35, name: 'Benson & Bingham - Downtown' },
{ id: 36, name: 'Bad Daddy\'s Burger Bar' },
{ id: 37, name: 'Taco Truck' },
{ id: 38, name: 'Loomis Express' },
{ id: 39, name: 'Phoenicia Association' },
{ id: 40, name: 'Northern Maverick Brewing Co' },
{ id: 41, name: 'Johnny\'s Hamburgers' },
{ id: 42, name: 'Cheerful House Chinese Cuisine' },
{ id: 43, name: 'Gold Medal Mortgage' },
{ id: 44, name: 'The Café Carnegie' },
{ id: 45, name: 'Ken Nakamura DC, CAFCI' },
{ id: 46, name: 'Spicy Pickle' },
{ id: 47, name: 'Greek Gyro Express' },
{ id: 48, name: 'Pita Q' },
{ id: 49, name: 'Athletic Gaines' },
{ id: 50, name: 'Budget Car Rental' },
{ id: 51, name: 'Shenanigans Bar & Grill' },
{ id: 52, name: 'Wine Up' },
{ id: 53, name: 'Danny\'s Family Car Wash' },
{ id: 54, name: 'Matteo\'s' },
{ id: 55, name: 'Cathédrale Christ Church de Montréal' },
{ id: 56, name: 'Deering Vintage' },
{ id: 57, name: 'Classic Kia' },
{ id: 58, name: 'Sin City Indian Motorcycle' },
{ id: 59, name: 'Papa Murphy\'s' },
{ id: 60, name: 'T-Mobile' },
{ id: 61, name: 'The Gucci Pooch Pet Spa' },
{ id: 62, name: 'The Horny Toad Saloon' },
{ id: 63, name: 'Canyon Falls Spa & Salon' },
{ id: 64, name: 'Scorpion Cafe' },
{ id: 65, name: 'House of Pepper' },
{ id: 66,
  name: 'TownePlace Suites by Marriott Cleveland Streetsboro' },
{ id: 67, name: 'Happy Moose Bar and Grill' },
{ id: 68, name: 'Erindale Family Restaurant' },
{ id: 69, name: 'Beatrice Keller Clinic' },
{ id: 70, name: 'The Garage Sports & Billiards' },
{ id: 71, name: 'Layalina Mediterranean Grill' },
{ id: 72, name: 'Tim Hortons' },
{ id: 73,
  name: 'Better Home and Garden Real Estate -Sonoran Desert Lifestyles' },
{ id: 74, name: 'Bear Rock Cafe' },
{ id: 75, name: 'Stampede Toyota' },
{ id: 76, name: 'Laptop Trades & Mobile Services' },
{ id: 77, name: 'Body Empowered' },
{ id: 78, name: 'Kevin\'s Pool Service' },
{ id: 79, name: 'Jung Thai Restaurant' },
{ id: 80, name: 'Willo & Root' },
{ id: 81, name: 'Dj Market' },
{ id: 82, name: 'Peter\'s Aluminum Prime' },
{ id: 83, name: 'Cafe La Bellitalia' },
{ id: 84, name: 'Expert Locksmith Paradise' },
{ id: 85, name: 'Orangetheory Fitness Gilbert - East' },
{ id: 86, name: 'Miss Saigon 88 Cafe' },
{ id: 87, name: 'The Car Connection' },
{ id: 88, name: 'Charlotte Russe' },
{ id: 89, name: 'Kanu & Associates' },
{ id: 90, name: 'Subway' },
{ id: 91, name: 'Ehwa J Bar' },
{ id: 92, name: 'Hello Sunshine' },
{ id: 93, name: 'Az Eddy\'s Ac' },
{ id: 94, name: 'Moreno\'s Mexican Grill' },
{ id: 95, name: 'Craque de Creme' },
{ id: 96, name: 'Sushi One' },
{ id: 97, name: 'SimonMed Imaging - Scottsdale/Mountain View' },
{ id: 98, name: 'Deluxe Shoe Repair' },
{ id: 99, name: 'Pacific Coast Landscaping and Pool' }, 
{ id: 100, name: 'Meline Daniel A MD' },
{ id: 101, name: 'Tocino Boys' },
{ id: 102, name: 'The Feasting Room' },
{ id: 103, name: 'Comfort Inn' },
{ id: 104, name: 'Imprezzio Marketing' },
{ id: 105, name: 'Parks Automotive' },
{ id: 106, name: 'The Football Factory' },
{ id: 107, name: 'Iron City Grille' },
{ id: 108, name: 'Koodo Mobile' },
{ id: 109, name: 'Sushi Kee' },
{ id: 110, name: 'FastMed Urgent Care' },
{ id: 111, name: 'Cobblestone Veterinary Care' },
{ id: 112, name: 'Second Chance Animal Rescue' },
{ id: 113, name: 'Circle K' },
{ id: 114, name: 'Aptive' },
{ id: 115, name: 'Prana Bodhi' },
{ id: 116, name: 'Travelodge by Wyndham Cleveland Lakewood' },
{ id: 117, name: 'Circle K' },
{ id: 118, name: 'Melt Bar and Grilled' },
{ id: 119, name: 'Country Cafe' },
{ id: 120, name: 'The Great American Pub' },
{ id: 121, name: 'Rôtisserie St-Hubert' },
{ id: 122, name: 'Western Beltway Trail' },
{ id: 123, name: 'Fuddruckers' },
{ id: 124, name: 'A2Z auto exclusive' },
{ id: 125, name: 'Gina\'s Place' },
{ id: 126, name: 'Mootown Creamery' },
{ id: 127, name: 'SAS Comfort Shoes' },
{ id: 128, name: 'The Source Shop' },
{ id: 129, name: 'Vynex Window Systems' },
{ id: 130, name: 'Food City' },
{ id: 131, name: 'Carine W' },
{ id: 132, name: 'Amazing Lash Studio - McDowell Mountain Ranch' },
{ id: 133, name: 'Ling & Louie\'s Asian Bar and Grill' },
{ id: 134, name: 'Deegie\'s Carma' },
{ id: 135, name: 'The Daily Glow' },
{ id: 136, name: 'Anabell Dillon Photography' },
{ id: 137, name: 'Vapor Smoke Shop' },
{ id: 138, name: 'Blush Salon AZ' },
{ id: 139, name: 'Let\'s Be Frank' },
{ id: 140, name: 'UPMC Mercy South Side Outpatient Center' },
{ id: 141, name: 'Stonebrook Clubhouse' },
{ id: 142, name: 'Floss Dental & Orthodontics' },
{ id: 143, name: 'Big Cat Boxing & Fitness' },
{ id: 144, name: 'Extra Space Storage' },
{ id: 145, name: 'Desert Wind Therapeutics' },
{ id: 146, name: 'Iuventus Medical Center' },
{ id: 147, name: 'Dickie\'s No Frills' },
{ id: 148, name: 'The Classic Barbershop and Shave Parlor' },
{ id: 149, name: 'THEcafe at THEhotel' },
{ id: 150, name: 'Ben Sherman' } ]

let categories = [
  "Active Life",
  "Fitness & Instruction",
  "Fitness/Exercise Equipment",
  "Shopping",
  "Vitamins & Supplements",
  "Food",
  "Grocery",
  "Orthodontists",
  "Dentists",
  "General Dentistry",
  "Health & Medical",
  "Midwives",
  "Health & Medical",
  "Specialty Food",
  "Food",
  "Bakeries",
  "Furniture Stores",
  "Shopping",
  "Home & Garden",
  "Mattresses",
  "Home Decor",
  "Hair Salons",
  "Men's Hair Salons",
  "Beauty & Spas",
  "Barbers",
  "Oral Surgeons",
  "Dentists",
  "Health & Medical",
  "Pediatric Dentists",
  "Baby Gear & Furniture",
  "Shopping",
  "Food",
  "Steakhouses",
  "Restaurants",
  "Delis",
  "Canadian (New)",
  "Delicatessen",
  "Session Photography",
  "Event Planning & Services",
  "Event Photography",
  "Photographers",
  "Data Recovery",
  "Car Stereo Installation",
  "Home Services",
  "IT Services & Computer Repair",
  "Home Theatre Installation",
  "Local Services",
  "Mobile Phone Repair",
  "Electronics Repair",
  "Automotive",
  "Hotels & Travel",
  "Hotels",
  "Event Planning & Services",
  "Specialty Schools",
  "Performing Arts",
  "Adult Education",
  "Arts & Entertainment",
  "Private Tutors",
  "Local Services",
  "Education",
  "Vocal Coach",
  "Musical Instrument Services",
  "Arts & Entertainment",
  "Venues & Event Spaces",
  "Nightlife",
  "Music Venues",
  "Shopping",
  "Event Planning & Services",
  "Restaurants",
  "Cafes",
  "Art Galleries",
  "Auto Repair",
  "Automotive",
  "Auto Parts & Supplies",
  "Burgers",
  "Restaurants",
  "Barbeque",
  "Middle Eastern",
  "Restaurants",
  "Lebanese",
  "Chicken Wings",
  "Office Equipment",
  "Shopping",
  "IT Services & Computer Repair",
  "Local Services",
  "Printing Services",
  "Hotels & Travel",
  "Venues & Event Spaces",
  "Hotels",
  "Event Planning & Services",
  "Health & Medical",
  "Chiropractors",
  "Beauty & Spas",
  "Hair Removal",
  "Day Spas",
  "Nail Salons",
  "Nurseries & Gardening",
  "Home & Garden",
  "Shopping",
  "Gift Shops",
  "Flowers & Gifts",
  "Florists",
  "General Dentistry",
  "Dentists",
  "Endodontists",
  "Cosmetic Dentists",
  "Health & Medical",
  "Salad",
  "Fast Food",
  "Soup",
  "Restaurants",
  "Delis",
  "Sandwiches",
  "Hair Salons",
  "Beauty & Spas",
  "American (Traditional)",
  "Restaurants",
  "Restaurants",
  "Pakistani",
  "Indian",
  "Event Planning & Services",
  "Valet Services",
  "Party & Event Planning",
  "Party Supplies",
  "Barbers",
  "Beauty & Spas",
  "Retirement Homes",
  "Health & Medical",
  "Gluten-Free",
  "Restaurants",
  "Breakfast & Brunch",
  "American (Traditional)",
  "Desserts",
  "Food",
  "Chinese",
  "Restaurants",
  "Coffee & Tea",
  "Pets",
  "Veterinarians",
  "Legal Services",
  "General Litigation",
  "Professional Services",
  "Lawyers",
  "Workers Compensation Law",
  "Personal Injury Law",
  "Burgers",
  "Fast Food",
  "Food",
  "Ice Cream & Frozen Yogurt",
  "Restaurants",
  "Restaurants",
  "Mexican",
  "Food Trucks",
  "Food",
  "Local Services",
  "Couriers & Delivery Services",
  "Shopping",
  "Men's Clothing",
  "Fashion",
  "Food",
  "Brewpubs",
  "Breweries",
  "Nightlife",
  "Restaurants",
  "Burgers",
  "Restaurants",
  "Juice Bars & Smoothies",
  "Food",
  "Chinese",
  "Home Services",
  "Real Estate",
  "Mortgage Brokers",
  "Restaurants",
  "American (New)",
  "Health & Medical",
  "Chiropractors",
  "Acupuncture",
  "Physical Therapy",
  "Restaurants",
  "Sandwiches",
  "American (New)",
  "Pizza",
  "Restaurants",
  "Salad",
  "Greek",
  "Sandwiches",
  "Restaurants",
  "Middle Eastern",
  "Boot Camps",
  "Active Life",
  "Gyms",
  "Fitness & Instruction",
  "Health & Medical",
  "Trainers",
  "Physical Therapy",
  "Interval Training Gyms",
  "Circuit Training Gyms",
  "Car Dealers",
  "Car Rental",
  "Hotels & Travel",
  "Automotive",
  "American (Traditional)",
  "Nightlife",
  "Bars",
  "Restaurants",
  "Nightlife",
  "Bars",
  "Automotive",
  "Car Wash",
  "Nightlife",
  "Restaurants",
  "Italian",
  "Seafood",
  "Bars",
  "Lounges",
  "Local Flavor",
  "Churches",
  "Religious Organizations",
  "Shopping",
  "Used",
  "Vintage & Consignment",
  "Fashion",
  "Tires",
  "Car Dealers",
  "Automotive",
  "Auto Repair",
  "Shopping",
  "Motorcycle Gear",
  "Automotive",
  "Motorcycle Dealers",
  "Motorcycle Repair",
  "Salad",
  "Gluten-Free",
  "Pizza",
  "Restaurants",
  "Mobile Phones",
  "Shopping",
  "Pets",
  "Pet Services",
  "Pet Groomers",
  "Pet Stores",
  "Nightlife",
  "Pubs",
  "Diners",
  "Bars",
  "Restaurants",
  "Beauty & Spas",
  "Makeup Artists",
  "Hair Extensions",
  "Shopping",
  "Hair Salons",
  "Day Spas",
  "Cosmetics & Beauty Supply",
  "Coffee & Tea",
  "Food",
  "Cafes",
  "Restaurants",
  "Restaurants",
  "Chinese",
  "Hotels",
  "Event Planning & Services",
  "Hotels & Travel",
  "Sports Bars",
  "American (Traditional)",
  "Bars",
  "Restaurants",
  "Nightlife",
  "Canadian (New)",
  "Restaurants",
  "Dermatologists",
  "Cosmetic Surgeons",
  "Health & Medical",
  "Surgeons",
  "Doctors",
  "Bars",
  "Nightlife",
  "Sports Bars",
  "Mediterranean",
  "Restaurants",
  "Middle Eastern",
  "Cafes",
  "Coffee & Tea",
  "Restaurants",
  "Bakeries",
  "Food",
  "Home Services",
  "Real Estate Agents",
  "Real Estate",
  "Real Estate Services",
  "Sandwiches",
  "Restaurants",
  "Auto Repair",
  "Auto Detailing",
  "Automotive",
  "Car Dealers",
  "Used Car Dealers",
  "Auto Parts & Supplies",
  "Electronics Repair",
  "Local Services",
  "Yoga",
  "Active Life",
  "Fitness & Instruction",
  "Home Services",
  "Pool Cleaners",
  "Thai",
  "Restaurants",
  "Hair Salons",
  "Waxing",
  "Nail Salons",
  "Hair Removal",
  "Beauty & Spas",
  "Grocery",
  "Food",
  "Specialty Food",
  "Fruits & Veggies",
  "Home Services",
  "Building Supplies",
  "Italian",
  "Pizza",
  "Restaurants",
  "Home Services",
  "Professional Services",
  "Keys & Locksmiths",
  "Fitness & Instruction",
  "Boot Camps",
  "Gyms",
  "Trainers",
  "Active Life",
  "Asian Fusion",
  "Restaurants",
  "Car Dealers",
  "Automotive",
  "Women's Clothing",
  "Accessories",
  "Shopping",
  "Fashion",
  "Personal Injury Law",
  "Immigration Law",
  "Lawyers",
  "Wills",
  "Trusts",
  "& Probates",
  "Professional Services",
  "DUI Law",
  "Estate Planning Law",
  "Criminal Defense Law",
  "Food",
  "Sandwiches",
  "Fast Food",
  "Restaurants",
  "Nightlife",
  "Korean",
  "Restaurants",
  "Bars",
  "Beauty & Spas",
  "Spray Tanning",
  "Tanning",
  "Heating & Air Conditioning/HVAC",
  "Home Services",
  "Restaurants",
  "Mexican",
  "Food",
  "Desserts",
  "Restaurants",
  "Sushi Bars",
  "Health & Medical",
  "Diagnostic Imaging",
  "Doctors",
  "Radiologists",
  "Diagnostic Services",
  "Local Services",
  "Shoe Repair",
  "Pool & Hot Tub Service",
  "Home Services",
  "Lighting Fixtures & Equipment",
  "Masonry/Concrete",
  "Foundation Repair",
  "Landscaping",
  "Hepatologists",
  "Doctors",
  "Health & Medical",
  "Gastroenterologist",
  "Restaurants",
  "Filipino",
  "Food",
  "Street Vendors",
  "French",
  "Restaurants",
  "Marketing",
  "Professional Services",
  "Web Design",
  "Auto Repair",
  "Towing",
  "Automotive",
  "Oil Change Stations",
  "Modern European",
  "Sports Bars",
  "Breakfast & Brunch",
  "Nightlife",
  "Restaurants",
  "American (Traditional)",
  "Bars",
  "Beer Bar",
  "Nightlife",
  "Restaurants",
  "American (Traditional)",
  "Bars",
  "Electronics",
  "Shopping",
  "Japanese",
  "Sushi Bars",
  "Restaurants",
  "Medical Centers",
  "Doctors",
  "Urgent Care",
  "Health & Medical",
  "Health & Medical",
  "Veterinarians",
  "Pets",
  "Acupuncture",
  "Pet Adoption",
  "Local Services",
  "Community Service/Non-Profit",
  "Pets",
  "Food",
  "Coffee & Tea",
  "Convenience Stores",
  "Gas Stations",
  "Automotive",
  "Local Services",
  "Pest Control",
  "Active Life",
  "Beauty & Spas",
  "Yoga",
  "Massage",
  "Fitness & Instruction",
  "Food",
  "Gas Stations",
  "Automotive",
  "Grocery",
  "Convenience Stores",
  "Comfort Food",
  "Sandwiches",
  "American (Traditional)",
  "Nightlife",
  "Bars",
  "Restaurants",
  "Pubs",
  "Diners",
  "Restaurants",
  "Breakfast & Brunch",
  "American (Traditional)",
  "Sports Bars",
  "Nightlife",
  "Pubs",
  "Bars",
  "Chicken Shop",
  "Restaurants",
  "Delis",
  "Barbeque",
  "Active Life",
  "Parks",
  "American (Traditional)",
  "Burgers",
  "Restaurants",
  "Automotive",
  "Auto Repair",
  "Breakfast & Brunch",
  "American (Traditional)",
  "Diners",
  "Restaurants",
  "Ice Cream & Frozen Yogurt",
  "Food",
  "Fashion",
  "Shopping",
  "Shoe Stores",
  "Shopping",
  "Local Services",
  "Professional Services",
  "Home Services",
  "Arts & Entertainment",
  "Lighting Fixtures & Equipment",
  "Photography Stores & Services",
  "Event Planning & Services",
  "Party Supplies",
  "Screen Printing",
  "Video/Film Production",
  "Building Supplies",
  "Door Sales/Installation",
  "Windows Installation",
  "Siding",
  "Glass & Mirrors",
  "Contractors",
  "Home Services",
  "Grocery",
  "Food",
  "Shopping",
  "Fashion",
  "Women's Clothing",
  "Eyelash Service",
  "Cosmetics & Beauty Supply",
  "Shopping",
  "Beauty & Spas",
  "Comfort Food",
  "Thai",
  "Chinese",
  "Asian Fusion",
  "Restaurants",
  "American (New)",
  "Hair Salons",
  "Beauty & Spas",
  "Women's Clothing",
  "Shopping",
  "Fashion",
  "Beauty & Spas",
  "Skin Care",
  "Session Photography",
  "Photographers",
  "Event Planning & Services",
  "Tobacco Shops",
  "Vape Shops",
  "Shopping",
  "Skin Care",
  "Hair Stylists",
  "Makeup Artists",
  "Beauty & Spas",
  "Hair Salons",
  "Massage",
  "Hair Extensions",
  "Eyelash Service",
  "Food Trucks",
  "Restaurants",
  "Hot Dogs",
  "Food",
  "Medical Centers",
  "Doctors",
  "Rehabilitation Center",
  "Health & Medical",
  "American (New)",
  "Restaurants",
  "Breakfast & Brunch",
  "Dentists",
  "Orthodontists",
  "General Dentistry",
  "Health & Medical",
  "Cosmetic Dentists",
  "Pediatric Dentists",
  "Active Life",
  "Fitness & Instruction",
  "Boxing",
  "Self Storage",
  "Local Services",
  "Beauty & Spas",
  "Day Spas",
  "Medical Centers",
  "Weight Loss Centers",
  "Medical Spas",
  "Beauty & Spas",
  "Health & Medical",
  "Men's Clothing",
  "Fashion",
  "Shopping",
  "Women's Clothing"
]